trigger: none

pool:
  name: Default

steps:
  - task: AzureCLI@2
    displayName: 'List SWA commands'
    inputs:
      azureSubscription: 'azure-vehicle-connection'
      scriptType: batch
      scriptLocation: inlineScript
      inlineScript: az staticwebapp --help