trigger: none

pool:
  name: Default

steps:
  - download: none

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: specific
      project: 'Vehicle Management'
      pipeline: 'dotnet-vehicle-management'
      artifactName: 'frontend-dist'
      targetPath: '$(Pipeline.Workspace)/frontend-dist'

  - script: npm install -g @azure/static-web-apps-cli@1.0.0
    displayName: 'Instalar SWA CLI v1'

  - task: AzureCLI@2
    displayName: 'Deploy para Azure Static Web Apps'
    inputs:
      azureSubscription: 'azure-vehicle-connection'
      scriptType: batch
      scriptLocation: inlineScript
      inlineScript: swa deploy "$(Pipeline.Workspace)/frontend-dist/frontend/browser" --deployment-token "e46f07cb82a1fb613aa1feac223dbfb60c05eeeacf1adcc5a035a9f921db80f307-844340c1-a033-450b-b333-1a470089398c00f2202074d07d0f" --env production --api-location ""